name: flutter_test_primaya
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  flutter_riverpod: ^2.3.10
  flutter_hooks: ^0.20.1
  equatable: ^2.0.5
  hooks_riverpod: ^2.3.10
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
